#!/bin/bash

echo "🚀 Final Deployment Hazırlığı"
echo "=============================="
echo ""
echo "✅ Build tamamlandı - dist klasörü hazır"
echo "✅ ws-resources.json eklendi - routing'ler doğru"
echo "✅ Walrus config ayarlandı"
echo ""
echo "📋 Şimdi Yapılacaklar:"
echo ""
echo "1️⃣  Cüzdanınızı Import Edin"
echo "   Private key'inizi kullanarak:"
echo "   $ sui client import <private-key> ed25519"
echo ""
echo "   VEYA seed phrase ile:"
echo "   $ sui keytool import \"<12-24 kelime>\" ed25519"
echo ""
echo "2️⃣  Cüzdanı Aktif Edin"
echo "   $ sui client switch --address 0x689bb7d13dd8f3e28e2338fe91a69832f022c098d83e13faf3fca70e9603db2f"
echo ""
echo "3️⃣  Bakiyeleri Kontrol Edin"
echo "   $ sui client gas"
echo ""
echo "4️⃣  Site'ı Publish Edin"
echo "   $ cd /home/hackathon/Desktop/SuiKnow"
echo "   $ site-builder --config .walrus/sites-config.yaml publish --epochs 53 dist"
echo ""
echo "5️⃣  Deployment Sonrası"
echo "   - 'Site objectID' değerini kopyalayın"
echo "   - Eğer farklıysa src/lib/walrusConfig.ts dosyasını güncelleyin"
echo "   - SuiNS domain'inizi yeni object ID'ye bağlayın (https://suins.io)"
echo ""
echo "💡 Önemli Notlar:"
echo "   - Testnet'te maksimum 53 epoch (≈53 gün) saklama"
echo "   - Her deployment yeni bir site object ID oluşturur"
echo "   - SuiNS domain'ini her seferinde güncellemeniz gerekmez"
echo "   - Mevcut object ID: 0xf33e8ed15c1e776205aade506a3281c8ce5d2b8d1059c2da4eec61040baad4ba"
echo ""
echo "🎯 Beklenen Sonuç:"
echo "   Site URL: https://suinks.trwal.app"
echo "   Profil URL: https://suinks.trwal.app/view/0x123..."
echo ""
echo "⚠️  Private Key Import Ederken:"
echo "   - Terminal'i başkalarına göstermeyin"
echo "   - Import sonrası: history -c (geçmişi temizle)"
echo "   - Sadece testnet cüzdanı kullanın"
