#!/bin/bash

echo "🔑 Cüzdan Import Rehberi"
echo "========================"
echo ""
echo "Cüzdan adresi: 0x689bb7d13dd8f3e28e2338fe91a69832f022c098d83e13faf3fca70e9603db2f"
echo ""
echo "Bu cüzdanı Sui CLI'ye import etmek için private key'iniz gerekiyor."
echo ""
echo "📝 Private Key Import Yöntemleri:"
echo ""
echo "1. Private Key ile import (Önerilen):"
echo "   sui client import <private-key> ed25519"
echo ""
echo "2. Keystore dosyası ile import:"
echo "   - Private key'i sui keystore formatında ekleyin"
echo "   - ~/.sui/sui_config/sui.keystore dosyasını düzenleyin"
echo ""
echo "3. Mnemonic/Seed Phrase ile import:"
echo "   sui keytool import <seed-phrase> ed25519"
echo ""
echo "⚠️  GÜVENLİK UYARISI:"
echo "   - Private key'i asla paylaşmayın"
echo "   - Sadece güvenilir cihazlarda kullanın"
echo "   - Import sonrası terminal geçmişini temizleyin: history -c"
echo ""
echo "✅ Import sonrası yapılacaklar:"
echo "   1. Cüzdanı aktif edin:"
echo "      sui client switch --address 0x689bb7d13dd8f3e28e2338fe91a69832f022c098d83e13faf3fca70e9603db2f"
echo ""
echo "   2. Bakiyeyi kontrol edin:"
echo "      sui client gas"
echo ""
echo "   3. Site'ı publish edin:"
echo "      cd /home/hackathon/Desktop/SuiKnow"
echo "      site-builder --config .walrus/sites-config.yaml publish --epochs 53 dist"
echo ""
echo "💡 Alternatif Çözüm (Private key import etmeden):"
echo "   Eğer bu cüzdan bir browser extension'da (Sui Wallet, Suiet vs.) kayıtlıysa,"
echo "   deploy scriptini browser üzerinden çalıştırabilirsiniz."
echo ""
echo "   Ya da mevcut aktif cüzdana (0x8bb7c4abb98549c8608e34c800c3548ef836b66f1b2a7d7ea35a7035101653ae)"
echo "   SUI ve WAL token transfer edebilirsiniz."
